### ISSUE TITLE
Fan pulsing on interrupts

### ISSUE THREAD

**Issue by sandhawke** [ru-ace/dell-fan-monitor#6]
Okay, this is weird.   Things have been great since #4 was resolved, except when I go mobile.  When I resume from suspend, on battery power, my laptop acts kind of like a phone with haptic feedback turned on. That is, whenever a key is pressed, the laptop vibrates a tiny bit. I'm pretty sure it's the fan being turned on for a small fraction of a second. Also, when I'm moving the mouse, it jumps like this continually, like maybe 5-10 times per second. The problem is resolved by rebooting.

I totally understand if this is too niche to worry about.  But if the mystery intrigues you, and you can think of some diagnostics I should try, let me know.

**Comment by ru-ace** [comment]
Sorry, but I have no idea what this could be, especially with keystroke and mouse move correlation.
Anyway, please check that you are using the latest version (1.2.2), because I found that sometimes (often after suspend mode) dell-fan-mon shuts down correctly (sets the maximum fan speed and restores BIOS control) cause it's got error from smm bios function.This fixed in latest version.
